<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ovm.proto

namespace Ovm;

use UnexpectedValueException;

/**
 * Protobuf type <code>ovm.Booze</code>
 */
class Booze
{
    /**
     * Generated from protobuf enum <code>BECHER = 0;</code>
     */
    const BECHER = 0;
    /**
     * Generated from protobuf enum <code>FERNET = 1;</code>
     */
    const FERNET = 1;
    /**
     * Generated from protobuf enum <code>JELINEK = 2;</code>
     */
    const JELINEK = 2;
    /**
     * Generated from protobuf enum <code>VIROZA = 3;</code>
     */
    const VIROZA = 3;

    private static $valueToName = [
        self::BECHER => 'BECHER',
        self::FERNET => 'FERNET',
        self::JELINEK => 'JELINEK',
        self::VIROZA => 'VIROZA',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

