<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ovm.proto

namespace Ovm;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ovm.MoravecRequest</code>
 */
class MoravecRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ovm.Mood mood = 1;</code>
     */
    private $mood = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $mood
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ovm::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ovm.Mood mood = 1;</code>
     * @return int
     */
    public function getMood()
    {
        return $this->mood;
    }

    /**
     * Generated from protobuf field <code>.ovm.Mood mood = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMood($var)
    {
        GPBUtil::checkEnum($var, \Ovm\Mood::class);
        $this->mood = $var;

        return $this;
    }

}

