<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ovm.proto

namespace Ovm;

use UnexpectedValueException;

/**
 * Protobuf type <code>ovm.Sport</code>
 */
class Sport
{
    /**
     * Generated from protobuf enum <code>TENNIS = 0;</code>
     */
    const TENNIS = 0;
    /**
     * Generated from protobuf enum <code>SKI = 1;</code>
     */
    const SKI = 1;
    /**
     * Generated from protobuf enum <code>F1 = 2;</code>
     */
    const F1 = 2;
    /**
     * Generated from protobuf enum <code>EGO = 3;</code>
     */
    const EGO = 3;

    private static $valueToName = [
        self::TENNIS => 'TENNIS',
        self::SKI => 'SKI',
        self::F1 => 'F1',
        self::EGO => 'EGO',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

